#!/bin/bash

# Stash unstaged changes
git stash -q --keep-index

# Clear notebook outputs
jupyter nbconvert --clear-output *.ipynb

# Stage updated files
git add -u

# Re-apply original unstaged changes
git stash pop -q