name: publish
on:
  push:
    branches:
      - main
    paths:
      - "*.ipynb"
      - "*.py"
      - .github/workflows/publish.yaml
      - .github/actions/publish-notebook
concurrency: publish
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Jupyter notebooks
        uses: okkema/notes/.github/actions/publish-notebook@main
        with:
          account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          r2_access_key: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY }}
          r2_secret_key: ${{ secrets.CLOUDFLARE_R2_SECRET_KEY }}
          r2_bucket: ${{ secrets.CLOUDFLARE_R2_BUCKET }}
          visibility: test
