name: deploy
on:
  push:
    branches:
      - main
    paths:
      - terraform/**
      - .terraformignore
      - .github/workflows/terraform.yaml
      - .nvmrc
concurrency: deploy
jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm ci --omit dev
      - name: Build Worker
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: dist
  terraform:
    runs-on: ubuntu-latest
    needs: [node]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        working-directory: terraform
        run: terraform init
      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate -no-color
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve